-- seed_safe_generation.sql
-- Safe helpers to generate new codes and insert seed data without causing unique constraint violations.
-- Usage:
-- 1) Run after your existing data is present: psql -f seed_safe_generation.sql
-- 2) This script creates sequences for generated codes (if not exists), sets them to the current max numeric suffix found in existing codes,
--    and demonstrates example inserts for stock_movements and sales_orders using nextval(...) to guarantee unique codes.

BEGIN;

-- ==========================
-- 1) Create sequences if missing
-- ==========================
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relkind = 'S' AND relname = 'seq_stock_movements_code') THEN
        CREATE SEQUENCE seq_stock_movements_code;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relkind = 'S' AND relname = 'seq_sales_orders_code') THEN
        CREATE SEQUENCE seq_sales_orders_code;
    END IF;
END$$;

-- ==========================
-- 2) Initialize sequences to max existing numeric suffix
--    This looks for codes like 'XK-GEN-00000001' and extracts the numeric part.
-- ==========================
SELECT setval('seq_stock_movements_code', COALESCE(MAX((regexp_replace(code, '\D', '', 'g'))::bigint), 0))
FROM stock_movements
WHERE code ~ '^XK-GEN-[0-9]+$';

SELECT setval('seq_sales_orders_code', COALESCE(MAX((regexp_replace(code, '\D', '', 'g'))::bigint), 0))
FROM sales_orders
WHERE code ~ '^SO-GEN-[0-9]+$';

-- At this point nextval('seq_stock_movements_code') will return max_existing + 1

-- ==========================
-- 3) Example: safe insert into stock_movements using sequence-generated codes
-- ==========================
-- Replace the SELECT block below with your actual generated data source (e.g., referencing sales_orders you want to create movements for).
-- This demonstrates inserting 100 new movements safely.

WITH source AS (
    SELECT id AS ref_order_id, code AS ref_order_code
    FROM sales_orders
    ORDER BY id DESC
    LIMIT 100  -- adjust how many new movements you want to create
)
INSERT INTO stock_movements (code, movement_type, warehouse_id, reference_doc, movement_date, created_by, notes, status, created_at)
SELECT
    format('XK-GEN-%s', lpad(nextval('seq_stock_movements_code')::text, 8, '0')),
    'XUAT_KHO',
    1 + (floor(random()*2))::int,
    s.ref_order_code,
    (current_date - (floor(random()*30)::int))::date,
    (SELECT id FROM sys_users ORDER BY random() LIMIT 1),
    'Safe-generated movement for ' || s.ref_order_code,
    'HOAN_THANH',
    now()
FROM source s;

-- ==========================
-- 4) Example: safe insert into sales_orders using sequence-generated codes
-- ==========================
-- Demonstrates creating 50 new sales_orders
WITH gen_customers AS (
    SELECT id FROM customers ORDER BY random() LIMIT 50
)
INSERT INTO sales_orders (code, quotation_id, customer_id, sales_rep_id, order_date, subtotal, discount_amount, tax_amount, total_amount, payment_status, status, notes, created_at)
SELECT
    format('SO-GEN-%s', lpad(nextval('seq_sales_orders_code')::text, 8, '0')),
    NULL,
    c.id,
    (SELECT id FROM sys_users WHERE role_id = 5 LIMIT 1),
    current_date,
    0,
    0,
    0,
    0,
    'CHUA_THANH_TOAN',
    'MOI',
    NULL,
    now()
FROM gen_customers c;

-- ==========================
-- 5) Helpful diagnostics: show new next values and top rows to verify
-- ==========================
SELECT nextval('seq_stock_movements_code') AS next_stock_movement_code_preview;
SELECT nextval('seq_sales_orders_code') AS next_sales_order_code_preview;

-- Show last 5 inserted stock_movements with the XK-GEN prefix
SELECT id, code, reference_doc, created_at FROM stock_movements WHERE code LIKE 'XK-GEN-%' ORDER BY id DESC LIMIT 5;

-- Show last 5 inserted sales_orders with SO-GEN prefix
SELECT id, code, customer_id, created_at FROM sales_orders WHERE code LIKE 'SO-GEN-%' ORDER BY id DESC LIMIT 5;

COMMIT;

-- ==========================
-- NOTES & recommendations
-- ==========================
-- 1) Use sequences for any autogenerated code that needs to be unique. Creating a dedicated sequence per code pattern is simple and robust.
-- 2) After running this script, your sequences will be ahead of existing max values, so future insertions using nextval(...) won't conflict.
-- 3) If you prefer human-friendly codes (e.g., include year), incorporate the year into the prefix but keep the numeric sequence separate, e.g. format('XK-2026-%s', lpad(nextval('seq_stock_movements_code')::text,8,'0'));
--    Do not try to reuse a sequence per-year without resetting safely.
-- 4) For concurrent inserts in application code, always use nextval on the sequence to avoid races.

-- End of seed_safe_generation.sql
